/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema;

/**
 *
 * @author diego
 */
public class FormularioMDI extends javax.swing.JFrame {

    /**
     * Creates new form FormularioMDI
     */
    public FormularioMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAgregar = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenuItem();
        mnuASalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuEUsuario = new javax.swing.JMenuItem();
        MnuAVentas = new javax.swing.JMenu();
        MnuAProductos = new javax.swing.JMenuItem();
        MnuAProveedor = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        mnuAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuAgregar.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        mnuAgregar.setText("Agregar Usuarios");
        mnuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAgregar);

        mnuEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, 0));
        mnuEliminar.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        mnuEliminar.setText("Eliminar Usuarios");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEliminar);

        mnuASalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuASalir.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        mnuASalir.setText("Salir");
        mnuASalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuASalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuASalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        cutMenuItem.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        cutMenuItem.setText("Cut");
        jMenu2.add(cutMenuItem);

        copyMenuItem.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        copyMenuItem.setText("Copy");
        jMenu2.add(copyMenuItem);

        pasteMenuItem.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        pasteMenuItem.setText("Paste");
        jMenu2.add(pasteMenuItem);

        deleteMenuItem.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        deleteMenuItem.setText("Delete");
        jMenu2.add(deleteMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 0, 0));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Estado");

        mnuEUsuario.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        mnuEUsuario.setText("Usuario");
        jMenu3.add(mnuEUsuario);

        jMenuBar1.add(jMenu3);

        MnuAVentas.setText("Registros");

        MnuAProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MnuAProductos.setText("Productos");
        MnuAProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAProductosActionPerformed(evt);
            }
        });
        MnuAVentas.add(MnuAProductos);

        MnuAProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MnuAProveedor.setText("Proveedor");
        MnuAProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAProveedorActionPerformed(evt);
            }
        });
        MnuAVentas.add(MnuAProveedor);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("Ventas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MnuAVentas.add(jMenuItem3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Clientes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MnuAVentas.add(jMenuItem5);

        jMenuBar1.add(MnuAVentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarActionPerformed
        // TODO add your handling code here:
        AgregarUsuarios au = new AgregarUsuarios();
        Escritorio.add(au);
        au.setVisible(true);

    }//GEN-LAST:event_mnuAgregarActionPerformed

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed
        // TODO add your handling code here:
        EliminarUsuario el = new EliminarUsuario();
        Escritorio.add(el);
        el.setVisible(true);
    }//GEN-LAST:event_mnuEliminarActionPerformed

    private void mnuASalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuASalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuASalirActionPerformed

    private void MnuAProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAProductosActionPerformed
        // TODO add your handling code here:
        Productos Pro = new Productos();
        Escritorio.add(Pro);
        Pro.setVisible(true);
    }//GEN-LAST:event_MnuAProductosActionPerformed

    private void MnuAProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAProveedorActionPerformed
        // TODO add your handling code here:
        Proveedor p = new Proveedor();
        Escritorio.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_MnuAProveedorActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Ventas de = new Ventas();
        Escritorio.add(de);
        de.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Clientes cl = new Clientes();
        Escritorio.add(cl);
        cl.setVisible(true);


    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MnuAProductos;
    private javax.swing.JMenuItem MnuAProveedor;
    private javax.swing.JMenu MnuAVentas;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mnuASalir;
    public javax.swing.JMenuItem mnuAgregar;
    public javax.swing.JMenuItem mnuEUsuario;
    public javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables
}
